# Generated by Django 4.2.30 on 2026-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_analysisresult_context_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="general_requirements_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
