# Generated by Django 4.2.30 on 2026-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_general_requirements_to_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="ocr_document_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
