# Generated by Django 4.2.30 on 2026-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_ocr_document_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
