# Generated by Django 4.2.30 on 2026-05-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="cumple_equipo",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="team_compliance_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="team_profiles_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
